"""empty message

Revision ID: 197fa18ff7d1
Revises: 780286366648
Create Date: 2021-12-29 18:19:54.159112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '197fa18ff7d1'
down_revision = '780286366648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'theme_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('themes', 'background_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'background_media',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('themes', 'background_rotate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('themes', 'font_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('themes', 'font_size',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('themes', 'accent_1',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'accent_2',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'accent_3',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('themes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('themes', 'accent_3',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'accent_2',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'accent_1',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'font_size',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('themes', 'font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('themes', 'font_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'background_rotate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('themes', 'background_media',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('themes', 'background_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'theme_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
