"""empty message

Revision ID: fe7561b87c1a
Revises: 52b5b6fec4cc
Create Date: 2021-10-25 02:35:19.111525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7561b87c1a'
down_revision = '52b5b6fec4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('tz_abbrev', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'tz_abbrev')
    # ### end Alembic commands ###
