"""empty message

Revision ID: f02b2429461c
Revises: 6da9bd4c5277
Create Date: 2021-10-26 21:58:13.229592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02b2429461c'
down_revision = '6da9bd4c5277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('theme_name', sa.String(length=50), nullable=False))
    op.add_column('themes', sa.Column('background_rotate', sa.Boolean(), nullable=False))
    op.add_column('themes', sa.Column('accent_1', sa.String(length=7), nullable=False))
    op.add_column('themes', sa.Column('accent_2', sa.String(length=7), nullable=False))
    op.add_column('themes', sa.Column('accent_3', sa.String(length=7), nullable=False))
    op.alter_column('themes', 'background_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'font_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('themes', 'font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('themes', 'font_size',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('themes', 'active')
    op.add_column('users', sa.Column('active_theme', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('theme_count', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_count')
    op.drop_column('users', 'active_theme')
    op.add_column('themes', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('themes', 'font_size',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('themes', 'font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('themes', 'font_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('themes', 'background_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.drop_column('themes', 'accent_3')
    op.drop_column('themes', 'accent_2')
    op.drop_column('themes', 'accent_1')
    op.drop_column('themes', 'background_rotate')
    op.drop_column('themes', 'theme_name')
    # ### end Alembic commands ###
