"""empty message

Revision ID: 52b5b6fec4cc
Revises: c09fb0d8025b
Create Date: 2021-10-21 14:15:47.621005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b5b6fec4cc'
down_revision = 'c09fb0d8025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'timezone')
    # ### end Alembic commands ###
