"""empty message

Revision ID: c09fb0d8025b
Revises: 4e9078445d53
Create Date: 2021-10-21 09:38:36.111159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c09fb0d8025b'
down_revision = '4e9078445d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('histories', 'search',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('histories', 'search',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
