"""empty message

Revision ID: 3ec198b2f06f
Revises: 6576cb47310d
Create Date: 2021-12-28 18:05:55.474576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec198b2f06f'
down_revision = '6576cb47310d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_theme', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_theme')
    # ### end Alembic commands ###
