"""empty message

Revision ID: 443b5ea7416e
Revises: 50e3060610e0
Create Date: 2021-10-29 23:02:04.809560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443b5ea7416e'
down_revision = '50e3060610e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'theme_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'theme_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
