"""empty message

Revision ID: 50e3060610e0
Revises: 
Create Date: 2021-10-28 15:03:55.283623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e3060610e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('active_theme', sa.SmallInteger(), nullable=True),
    sa.Column('theme_count', sa.SmallInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_media', sa.String(length=1000), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search', sa.String(length=1000), nullable=True),
    sa.Column('visit', sa.String(length=1000), nullable=True),
    sa.Column('tz', sa.String(length=50), nullable=False),
    sa.Column('tz_abbrev', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=50), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('background_media', sa.String(length=1000), nullable=True),
    sa.Column('background_rotate', sa.String(), nullable=False),
    sa.Column('font_color', sa.String(length=7), nullable=False),
    sa.Column('font_family', sa.String(length=50), nullable=False),
    sa.Column('font_size', sa.String(length=4), nullable=False),
    sa.Column('accent_1', sa.String(length=7), nullable=False),
    sa.Column('accent_2', sa.String(length=7), nullable=False),
    sa.Column('accent_3', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.drop_table('histories')
    op.drop_table('users')
    # ### end Alembic commands ###
