"""empty message

Revision ID: 6576cb47310d
Revises: 6e7b6891f40a
Create Date: 2021-11-13 08:53:31.154631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6576cb47310d'
down_revision = '6e7b6891f40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clock_24', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clock_24')
    # ### end Alembic commands ###
