"""empty message

Revision ID: 6e7b6891f40a
Revises: 55e01247578b
Create Date: 2021-11-13 00:31:55.308882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7b6891f40a'
down_revision = '55e01247578b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clock_24')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clock_24', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
