"""empty message

Revision ID: 780286366648
Revises: 3ec198b2f06f
Create Date: 2021-12-28 18:27:04.057124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780286366648'
down_revision = '3ec198b2f06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_theme', sa.SmallInteger(), nullable=True))
    op.drop_column('users', 'active_theme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_theme', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'custom_theme')
    # ### end Alembic commands ###
