"""empty message

Revision ID: 9c3e3afa7278
Revises: bf5bd1bc63ba
Create Date: 2021-11-04 11:40:37.736151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3e3afa7278'
down_revision = 'bf5bd1bc63ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clock_24', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clock_24')
    # ### end Alembic commands ###
