"""empty message

Revision ID: bf5bd1bc63ba
Revises: 60da8b289af0
Create Date: 2021-10-31 23:39:28.474751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5bd1bc63ba'
down_revision = '60da8b289af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_theme',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_theme',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
