"""empty message

Revision ID: c40338aea6c8
Revises: 047e922bf3d7
Create Date: 2021-10-30 11:37:46.839459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40338aea6c8'
down_revision = '047e922bf3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('background_rotate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'background_rotate')
    # ### end Alembic commands ###
