"""empty message

Revision ID: eca12f24e564
Revises: 319a024fdf7c
Create Date: 2021-10-30 03:31:18.201999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca12f24e564'
down_revision = '319a024fdf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_theme',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active_theme',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
